import { PlaceHolderImages } from './placeholder-images';
import type { Product, Category, Order, Customer, Review, BlogPost } from './types';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find((img) => img.id === id);
  return {
    id,
    url: image?.imageUrl || 'https://picsum.photos/seed/placeholder/600/600',
    alt: image?.description || 'Placeholder image',
  };
};

export const categories: Category[] = [
  { id: 'cat-1', name: 'Pillows', slug: 'pillows' },
  { id: 'cat-2', name: 'Cushions', slug: 'cushions' },
  { id: 'cat-3', name: 'Mattresses', slug: 'mattresses' },
  { id: 'cat-4', name: 'Covers', slug: 'covers' },
];

export const products: Product[] = [
  // Pillows
  {
    id: 'pillow-001',
    name: 'Micro Fiber Pillow',
    description: 'Ultra-soft microfiber pillow for a comfortable night\'s sleep. Hypoallergenic and machine washable.',
    price: 29.99,
    category: categories[0],
    images: [findImage('prod-1')],
    stock: 120,
    sku: 'PIL-MF-01',
    rating: 4.5,
    reviewCount: 150,
  },
  {
    id: 'pillow-002',
    name: 'Quilted Pillow',
    description: 'Elegant quilted pillow that provides both support and style. Features a premium cotton cover.',
    price: 39.99,
    category: categories[0],
    images: [findImage('prod-2')],
    stock: 80,
    sku: 'PIL-QLT-01',
    rating: 4.7,
    reviewCount: 95,
  },
  {
    id: 'pillow-003',
    name: 'Contour Memory Pillow',
    description: 'Ergonomically designed memory foam pillow that contours to your head and neck for optimal support.',
    price: 59.99,
    category: categories[0],
    images: [findImage('prod-3')],
    stock: 60,
    sku: 'PIL-MEM-01',
    rating: 4.8,
    reviewCount: 210,
  },
  {
    id: 'pillow-004',
    name: 'King Size Hotel Pillow',
    description: 'Experience luxury with our king-sized hotel collection pillow. Plush, supportive, and perfect for a great night\'s sleep.',
    price: 79.99,
    category: categories[0],
    images: [findImage('prod-4')],
    stock: 40,
    sku: 'PIL-HOT-KS-01',
    rating: 4.9,
    reviewCount: 320,
  },
  {
    id: 'pillow-005',
    name: 'Microfiber Bolster Pillow',
    description: 'A versatile bolster pillow made from soft microfiber. Ideal for back support or as a decorative accent.',
    price: 34.99,
    category: categories[0],
    images: [findImage('prod-5')],
    stock: 75,
    sku: 'PIL-BOL-MF-01',
    rating: 4.6,
    reviewCount: 80,
  },
  // Cushions
  {
    id: 'cushion-001',
    name: 'Microfiber Cushion Pillow',
    description: 'Soft and plush microfiber cushion, perfect for adding comfort and style to your living space.',
    price: 19.99,
    category: categories[1],
    images: [findImage('prod-6')],
    stock: 200,
    sku: 'CSH-MF-01',
    rating: 4.5,
    reviewCount: 180,
  },
  {
    id: 'cushion-002',
    name: 'King Size Cushion pillow',
    description: 'Oversized king cushion pillow for ultimate lounging comfort. Great for floor seating or as a statement piece.',
    price: 49.99,
    category: categories[1],
    images: [findImage('prod-7')],
    stock: 50,
    sku: 'CSH-KS-01',
    rating: 4.7,
    reviewCount: 110,
  },
  // Mattresses
  {
    id: 'mattress-001',
    name: 'Polyurethane King Size Mattress',
    description: 'A comfortable and durable king-sized mattress made from high-density polyurethane foam.',
    price: 499.99,
    category: categories[2],
    images: [findImage('prod-8')],
    stock: 20,
    sku: 'MAT-PU-KS-01',
    rating: 4.6,
    reviewCount: 120,
  },
  {
    id: 'mattress-002',
    name: 'Three Foldable EPE Mattress',
    description: 'A convenient and portable three-fold mattress, perfect for guests or small spaces. Made from durable EPE foam.',
    price: 149.99,
    category: categories[2],
    images: [findImage('prod-9')],
    stock: 35,
    sku: 'MAT-3F-EPE-01',
    rating: 4.4,
    reviewCount: 90,
  },
  {
    id: 'mattress-003',
    name: 'Sofa Cum Bed Mattress',
    description: 'A versatile mattress designed to fit most sofa beds, providing a comfortable sleeping surface for your guests.',
    price: 249.99,
    category: categories[2],
    images: [findImage('prod-10')],
    stock: 25,
    sku: 'MAT-SCB-01',
    rating: 4.5,
    reviewCount: 105,
  },
  // Covers
  {
    id: 'cover-001',
    name: 'King Size Mattress Zipper Cover',
    description: 'Protect your mattress with this king-sized zipper cover. Easy to remove and machine washable.',
    price: 49.99,
    category: categories[3],
    images: [findImage('prod-11')],
    stock: 90,
    sku: 'COV-MAT-KS-ZIP-01',
    rating: 4.7,
    reviewCount: 130,
  },
  {
    id: 'cover-002',
    name: 'King Size Water Proof Zipper Cover',
    description: 'A fully waterproof zipper cover to protect your king-sized mattress from spills and accidents.',
    price: 69.99,
    category: categories[3],
    images: [findImage('prod-12')],
    stock: 70,
    sku: 'COV-MAT-KS-WP-ZIP-01',
    rating: 4.8,
    reviewCount: 160,
  },
  {
    id: 'cover-003',
    name: 'Mattress Elastic Protector',
    description: 'An easy-to-use elastic mattress protector that fits snugly over your mattress, protecting it from dust and allergens.',
    price: 39.99,
    category: categories[3],
    images: [findImage('prod-13')],
    stock: 110,
    sku: 'COV-MAT-PRO-EL-01',
    rating: 4.6,
    reviewCount: 140,
  },
];


export const orders: Order[] = [
  { id: 'ORD-001', customerName: 'Alice Johnson', customerEmail: 'alice@example.com', date: '2023-10-26', total: 411.98, status: 'Delivered', items: 2 },
  { id: 'ORD-002', customerName: 'Bob Williams', customerEmail: 'bob@example.com', date: '2023-10-25', total: 249.99, status: 'Shipped', items: 1 },
  { id: 'ORD-003', customerName: 'Charlie Brown', customerEmail: 'charlie@example.com', date: '2023-10-25', total: 899.00, status: 'Processing', items: 1 },
  { id: 'ORD-004', customerName: 'Diana Prince', customerEmail: 'diana@example.com', date: '2023-10-24', total: 12.99, status: 'Pending', items: 1 },
  { id: 'ORD-005', customerName: 'Ethan Hunt', customerEmail: 'ethan@example.com', date: '2023-10-23', total: 349.00, status: 'Canceled', items: 1 },
  { id: 'ORD-006', customerName: 'Fiona Glenanne', customerEmail: 'fiona@example.com', date: '2023-10-22', total: 479.49, status: 'Delivered', items: 2 },
];

export const customers: Customer[] = [
  { id: 'CUST-001', name: 'Alice Johnson', email: 'alice@example.com', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d', totalSpent: 1250.75, orderCount: 5, registeredDate: '2023-01-15' },
  { id: 'CUST-002', name: 'Bob Williams', email: 'bob@example.com', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d', totalSpent: 850.50, orderCount: 3, registeredDate: '2023-03-22' },
  { id: 'CUST-003', name: 'Charlie Brown', email: 'charlie@example.com', avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d', totalSpent: 2300.00, orderCount: 8, registeredDate: '2022-11-30' },
  { id: 'CUST-004', name: 'Diana Prince', email: 'diana@example.com', avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d', totalSpent: 300.20, orderCount: 2, registeredDate: '2023-05-10' },
];

export const reviews: Review[] = [
    { id: 'REV-001', customerName: 'Alice Johnson', rating: 5, title: 'Absolutely love it!', comment: 'The smart watch is amazing. The battery life is great and it looks very stylish.', date: '2023-09-01' },
    { id: 'REV-002', customerName: 'Bob Williams', rating: 4, title: 'Very good headphones', comment: 'The noise cancellation is effective, but the fit could be a bit more comfortable for long sessions.', date: '2023-08-28' },
];

export const blogPosts: BlogPost[] = [
  {
    id: 'blog-post-1',
    title: 'The Ultimate Guide to Choosing the Perfect Pillow',
    slug: 'perfect-pillow-guide',
    author: 'Jane Doe',
    date: 'Oct 26, 2023',
    excerpt: 'Finding the right pillow is crucial for a good night\'s sleep. In this guide, we cover everything from materials to firmness to help you make the best choice.',
    imageUrl: findImage('blog-1').url,
    imageAlt: 'A person sleeping comfortably on a pillow.',
    featured: true,
  },
  {
    id: 'blog-post-2',
    title: 'How to Style Your Living Room with Cushions',
    slug: 'styling-with-cushions',
    author: 'John Smith',
    date: 'Oct 22, 2023',
    excerpt: 'Cushions are a powerful design tool. Learn how to use different textures, colors, and sizes to transform your living space.',
    imageUrl: findImage('blog-2').url,
    imageAlt: 'A stylish living room with decorative cushions on a sofa.',
    featured: true,
  },
  {
    id: 'blog-post-3',
    title: 'Mattress 101: A Comprehensive Guide',
    slug: 'mattress-101',
    author: 'Emily White',
    date: 'Oct 18, 2023',
    excerpt: 'From memory foam to innerspring, buying a mattress can be confusing. Our guide breaks down the types and features to consider.',
    imageUrl: findImage('blog-3').url,
    imageAlt: 'Cross-section of a mattress showing different layers.',
    featured: false,
  },
  {
    id: 'blog-post-4',
    title: '5 Reasons to Use a Mattress Protector',
    slug: 'why-use-mattress-protector',
    author: 'Michael Brown',
    date: 'Oct 15, 2023',
    excerpt: 'A mattress protector is a small investment that can save you a lot of trouble. Here are five key benefits to protecting your mattress.',
    imageUrl: findImage('blog-4').url,
    imageAlt: 'A person fitting a mattress protector on a bed.',
    featured: false,
  },
];
