import { PlaceHolderImages } from './placeholder-images';
import type { Product, Category, Order, Customer, Review, BlogPost, PaymentStatus, OrderStatus } from './types';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find((img) => img.id === id);
  return {
    id,
    url: image?.imageUrl || 'https://picsum.photos/seed/placeholder/600/600',
    alt: image?.description || 'Placeholder image',
  };
};

export const categories: Category[] = [
  { id: 'cat-1', name: 'Pillow', slug: 'pillow' },
  { id: 'cat-2', name: 'Mattress', slug: 'mattress' },
  { id: 'cat-3', name: 'Covers', slug: 'covers' },
];

export const products: Product[] = [
  {
    id: 'pillow-001',
    name: 'Micro Fiber Pillow',
    description: 'Ultra-soft microfiber pillow for a comfortable night\'s sleep. Hypoallergenic and machine washable.',
    price: 29.99,
    finalPrice: 29.99,
    category: categories[0],
    images: [findImage('prod-1'), findImage('prod-1b'), findImage('prod-1c')],
    primaryImageIndex: 0,
    stock: 120,
    variants: [
      { id: 'v1', size: 'Standard', stock: 50 },
      { id: 'v2', size: 'Queen', stock: 40 },
      { id: 'v3', size: 'King', stock: 30 },
    ],
    isFeatured: true,
    isBestSeller: false,
    isEnabled: true,
    seoTitle: 'Micro Fiber Pillow - Soft & Hypoallergenic',
    seoMetaDescription: 'Get the best sleep with our ultra-soft and hypoallergenic micro fiber pillow. Machine washable and durable.',
    seoKeywords: ['pillow', 'microfiber', 'hypoallergenic', 'sleep'],
    slug: 'micro-fiber-pillow',
    sku: 'PIL-MF-01',
    rating: 4.5,
    reviewCount: 150,
  },
  {
    id: 'mattress-001',
    name: 'Polyurethane King Size Mattress',
    description: 'A comfortable and durable king-sized mattress made from high-density polyurethane foam.',
    price: 499.99,
    discount: { type: 'percentage', value: 10 },
    finalPrice: 449.99,
    category: categories[1],
    images: [findImage('prod-8'), findImage('prod-8b')],
    primaryImageIndex: 0,
    stock: 20,
    variants: [
      { id: 'v1', thickness: '6 inch', stock: 10, price: 499.99 },
      { id: 'v2', thickness: '8 inch', stock: 10, price: 549.99 },
    ],
    isFeatured: false,
    isBestSeller: true,
    isEnabled: true,
    seoTitle: 'King Size Polyurethane Mattress',
    seoMetaDescription: 'Experience ultimate comfort with our durable king-size polyurethane foam mattress.',
    seoKeywords: ['mattress', 'king size', 'polyurethane', 'foam'],
    slug: 'polyurethane-king-mattress',
    sku: 'MAT-PU-KS-01',
    rating: 4.6,
    reviewCount: 120,
  },
    {
    id: 'cover-001',
    name: 'King Size Mattress Zipper Cover',
    description: 'Protect your mattress with this king-sized zipper cover. Easy to remove and machine washable.',
    price: 49.99,
    finalPrice: 49.99,
    category: categories[2],
    images: [findImage('prod-11')],
    primaryImageIndex: 0,
    stock: 90,
    variants: [
        {id: 'v1', color: 'White', stock: 50},
        {id: 'v2', color: 'Grey', stock: 40},
    ],
    isFeatured: false,
    isBestSeller: false,
    isEnabled: true,
    seoTitle: 'King Size Mattress Zipper Cover',
    seoMetaDescription: 'Keep your mattress clean with our easy-to-use king size zipper cover. Machine washable.',
    seoKeywords: ['mattress cover', 'zipper cover', 'king size'],
    slug: 'king-mattress-zipper-cover',
    sku: 'COV-MAT-KS-ZIP-01',
    rating: 4.7,
    reviewCount: 130,
  },
  // Adding a few more products to have a good list
  {
    id: 'pillow-002',
    name: 'Quilted Pillow',
    description: 'Elegant quilted pillow that provides both support and style. Features a premium cotton cover.',
    price: 39.99,
    finalPrice: 39.99,
    category: categories[0],
    images: [findImage('prod-2')],
    primaryImageIndex: 0,
    stock: 80,
    variants: [],
    isFeatured: true,
    isBestSeller: true,
    isEnabled: true,
    seoTitle: 'Elegant Quilted Pillow',
    seoMetaDescription: 'Add a touch of elegance and comfort to your bedroom with our premium quilted pillow.',
    seoKeywords: ['pillow', 'quilted', 'cotton'],
    slug: 'quilted-pillow',
    sku: 'PIL-QLT-01',
    rating: 4.7,
    reviewCount: 95,
  },
    {
    id: 'mattress-002',
    name: 'Three Foldable EPE Mattress',
    description: 'A convenient and portable three-fold mattress, perfect for guests or small spaces. Made from durable EPE foam.',
    price: 149.99,
    finalPrice: 149.99,
    category: categories[1],
    images: [findImage('prod-9')],
    primaryImageIndex: 0,
    stock: 35,
    variants: [],
    isFeatured: false,
    isBestSeller: false,
    isEnabled: false,
    seoTitle: 'Foldable EPE Mattress',
    seoMetaDescription: 'A portable and convenient three-fold EPE mattress, ideal for guests and travel.',
    seoKeywords: ['mattress', 'foldable', 'portable', 'EPE foam'],
    slug: 'three-foldable-epe-mattress',
    sku: 'MAT-3F-EPE-01',
    rating: 4.4,
    reviewCount: 90,
  },
];


export const orders: Order[] = [
  { id: 'ORD-001', customerName: 'Alice Johnson', customerEmail: 'alice@example.com', date: '2023-10-26', total: 411.98, status: 'Delivered', items: 2, paymentStatus: 'Paid' },
  { id: 'ORD-002', customerName: 'Bob Williams', customerEmail: 'bob@example.com', date: '2023-10-25', total: 249.99, status: 'Shipped', items: 1, paymentStatus: 'Paid' },
  { id: 'ORD-003', customerName: 'Charlie Brown', customerEmail: 'charlie@example.com', date: '2023-10-25', total: 899.00, status: 'Processing', items: 1, paymentStatus: 'Pending' },
  { id: 'ORD-004', customerName: 'Diana Prince', customerEmail: 'diana@example.com', date: '2023-10-24', total: 12.99, status: 'Pending', items: 1, paymentStatus: 'Paid' },
  { id: 'ORD-005', customerName: 'Ethan Hunt', customerEmail: 'ethan@example.com', date: '2023-10-23', total: 349.00, status: 'Canceled', items: 1, paymentStatus: 'Failed' },
  { id: 'ORD-006', customerName: 'Fiona Glenanne', customerEmail: 'fiona@example.com', date: '2023-10-22', total: 479.49, status: 'Delivered', items: 2, paymentStatus: 'Paid' },
];

export const customers: Customer[] = [
  { id: 'CUST-001', name: 'Alice Johnson', email: 'alice@example.com', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d', totalSpent: 1250.75, orderCount: 5, registeredDate: '2023-01-15' },
  { id: 'CUST-002', name: 'Bob Williams', email: 'bob@example.com', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d', totalSpent: 850.50, orderCount: 3, registeredDate: '2023-03-22' },
  { id: 'CUST-003', name: 'Charlie Brown', email: 'charlie@example.com', avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d', totalSpent: 2300.00, orderCount: 8, registeredDate: '2022-11-30' },
  { id: 'CUST-004', name: 'Diana Prince', email: 'diana@example.com', avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d', totalSpent: 300.20, orderCount: 2, registeredDate: '2023-05-10' },
];

export const reviews: Review[] = [
    { id: 'REV-001', customerName: 'Alice Johnson', rating: 5, title: 'Absolutely love it!', comment: 'The smart watch is amazing. The battery life is great and it looks very stylish.', date: '2023-09-01' },
    { id: 'REV-002', customerName: 'Bob Williams', rating: 4, title: 'Very good headphones', comment: 'The noise cancellation is effective, but the fit could be a bit more comfortable for long sessions.', date: '2023-08-28' },
];

export const blogPosts: BlogPost[] = [
  {
    id: 'blog-post-1',
    title: 'The Ultimate Guide to Choosing the Perfect Pillow',
    slug: 'perfect-pillow-guide',
    author: 'Jane Doe',
    date: 'Oct 26, 2023',
    excerpt: 'Finding the right pillow is crucial for a good night\'s sleep. In this guide, we cover everything from materials to firmness to help you make the best choice.',
    imageUrl: findImage('blog-1').url,
    imageAlt: 'A person sleeping comfortably on a pillow.',
    featured: true,
  },
  {
    id: 'blog-post-2',
    title: 'How to Style Your Living Room with Cushions',
    slug: 'styling-with-cushions',
    author: 'John Smith',
    date: 'Oct 22, 2023',
    excerpt: 'Cushions are a powerful design tool. Learn how to use different textures, colors, and sizes to transform your living space.',
    imageUrl: findImage('blog-2').url,
    imageAlt: 'A stylish living room with decorative cushions on a sofa.',
    featured: true,
  },
  {
    id: 'blog-post-3',
    title: 'Mattress 101: A Comprehensive Guide',
    slug: 'mattress-101',
    author: 'Emily White',
    date: 'Oct 18, 2023',
    excerpt: 'From memory foam to innerspring, buying a mattress can be confusing. Our guide breaks down the types and features to consider.',
    imageUrl: findImage('blog-3').url,
    imageAlt: 'Cross-section of a mattress showing different layers.',
    featured: false,
  },
  {
    id: 'blog-post-4',
    title: '5 Reasons to Use a Mattress Protector',
    slug: 'why-use-mattress-protector',
    author: 'Michael Brown',
    date: 'Oct 15, 2023',
    excerpt: 'A mattress protector is a small investment that can save you a lot of trouble. Here are five key benefits to protecting your mattress.',
    imageUrl: findImage('blog-4').url,
    imageAlt: 'A person fitting a mattress protector on a bed.',
    featured: false,
  },
];
